version: "3.8"

services:
  # === Cloud Commander ===
  cloudcmd:
    image: coderaiser/cloudcmd
    container_name: cloudcmd
    environment:
      - AUTH=true
      - USER=admin
      - PASS=admin
    labels:
      - "traefik.http.routers.drive.rule=Host(`drive.dxi`)"
    networks:
      - appnet
    volumes:
      - ./data:/mnt/fs
    restart: always

  # === Joomla ===
  joomla:
    image: joomla
    container_name: joomla
    depends_on:
      - joomla-db
    environment:
      - JOOMLA_DB_HOST=joomla-db
      - JOOMLA_DB_USER=joomla
      - JOOMLA_DB_PASSWORD=joomlapass
      - JOOMLA_DB_NAME=joomla
    labels:
      - "traefik.http.routers.joomla.rule=Host(`joomla.dxi`)"
    networks:
      - appnet
    volumes:
      - joomla-data:/var/www/html
    restart: always


  joomla-db:
    image: mysql:8.0
    container_name: joomla-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomlapass
    volumes:
      - joomla-db:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5


  # === Wiki.js ===
  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres-wiki
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    depends_on:
      - postgres-wiki
    labels:
      - "traefik.http.routers.wikijs.rule=Host(`wiki.dxi`)"
    networks:
      - appnet

  postgres-wiki:
    image: postgres:15
    container_name: postgres-wiki
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    volumes:
      - wikijs-db:/var/lib/postgresql/data
    networks:
      - appnet



  # === Focalboard ===
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    environment:
      - DB_TYPE=sqlite3
    labels:
      - "traefik.http.routers.focalboard.rule=Host(`jira.dxi`)"
    networks:
      - appnet
    volumes:
      - focalboard-data:/opt/focalboard/data
    restart: always

  # === Traefik Proxy ===
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8082:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/Mexico_City'
      WEBPASSWORD: 'admin'
      ServerIP: 192.168.0.14
    labels:
      - "traefik.http.routers.pihole.rule=Host(`pihole.dxi`)"
    volumes:
      - pihole-config:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    networks:
      - appnet
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped


volumes:
  wikijs-db:
  joomla-data:
  joomla-db:
  focalboard-data:
  pihole-config:
  pihole-dnsmasq:


networks:
  appnet:
    driver: bridge
